-- MySQL Script generated by MySQL Workbench
-- Ter 21 Fev 2017 13:48:20 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proconpb_naoperturbe_v2
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proconpb_naoperturbe_v2` ;

-- -----------------------------------------------------
-- Schema proconpb_naoperturbe_v2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proconpb_naoperturbe_v2` DEFAULT CHARACTER SET utf8 ;
USE `proconpb_naoperturbe_v2` ;

-- -----------------------------------------------------
-- Table `proconpb_naoperturbe_v2`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proconpb_naoperturbe_v2`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `senha` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `type` VARCHAR(6) CHARACTER SET 'utf8' NOT NULL,
  `cep` VARCHAR(9) NOT NULL,
  `rua` VARCHAR(255) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(150) NOT NULL,
  `numero` INT(11) NULL,
  `complemento` VARCHAR(255) NULL,
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proconpb_naoperturbe_v2`.`pessoa_fisica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proconpb_naoperturbe_v2`.`pessoa_fisica` (
  `id_pessoa_fisica` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT(11) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `uf` VARCHAR(2) NOT NULL,
  `rg` VARCHAR(8) NOT NULL,
  `data_expedicao` VARCHAR(8) NOT NULL,
  `orgao_expedidor` VARCHAR(45) NOT NULL,
  UNIQUE INDEX `usuario_id_usuario_UNIQUE` (`usuario_id_usuario` ASC),
  PRIMARY KEY (`id_pessoa_fisica`),
  UNIQUE INDEX `id_pessoa_fisica_UNIQUE` (`id_pessoa_fisica` ASC),
  CONSTRAINT `fk_pessoa_fisica_1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `proconpb_naoperturbe_v2`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proconpb_naoperturbe_v2`.`pessoa_juridica`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proconpb_naoperturbe_v2`.`pessoa_juridica` (
  `id_pessoa_juridica` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT(11) NOT NULL,
  `cnpj` VARCHAR(19) NOT NULL,
  `status_telemarketing` INT(1) NOT NULL,
  UNIQUE INDEX `usuario_id_usuario_UNIQUE` (`usuario_id_usuario` ASC),
  PRIMARY KEY (`id_pessoa_juridica`),
  UNIQUE INDEX `id_pessoa_juridica_UNIQUE` (`id_pessoa_juridica` ASC),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC),
  CONSTRAINT `fk_pessoa_juridica_1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `proconpb_naoperturbe_v2`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 27
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proconpb_naoperturbe_v2`.`telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proconpb_naoperturbe_v2`.`telefone` (
  `id_telefone` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT(11) NOT NULL,
  `status_bloqueio` INT(1) NOT NULL,
  `telefone_numero` VARCHAR(14) CHARACTER SET 'utf8' NOT NULL,
  `data_cadastro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE INDEX `telefone_numero_UNIQUE` (`telefone_numero` ASC),
  INDEX `fk_telefone_1_idx` (`usuario_id_usuario` ASC),
  PRIMARY KEY (`id_telefone`),
  UNIQUE INDEX `id_telefone_UNIQUE` (`id_telefone` ASC),
  CONSTRAINT `fk_telefone_1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `proconpb_naoperturbe_v2`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
