-- MySQL Script generated by MySQL Workbench
-- Ter 25 Out 2016 02:10:47 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proconpb_naopertube
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proconpb_naopertube` ;

-- -----------------------------------------------------
-- Schema proconpb_naopertube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proconpb_naopertube` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `proconpb_naopertube` ;

-- -----------------------------------------------------
-- Table `proconpb_naopertube`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proconpb_naopertube`.`usuario` ;

CREATE TABLE IF NOT EXISTS `proconpb_naopertube`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `senha` VARCHAR(60) CHARACTER SET 'utf8' NOT NULL,
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `proconpb_naopertube`.`itens_bloqueio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proconpb_naopertube`.`itens_bloqueio` ;

CREATE TABLE IF NOT EXISTS `proconpb_naopertube`.`itens_bloqueio` (
  `nome_operadora` VARCHAR(25) NULL,
  `telefone` VARCHAR(11) NOT NULL,
  `status_bloqueio` INT NOT NULL,
  `data_cadastro` DATETIME NOT NULL,
  `data_atualizacao` DATETIME NOT NULL,
  `id_itens` INT NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC),
  PRIMARY KEY (`id_itens`),
  UNIQUE INDEX `id_itens_UNIQUE` (`id_itens` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proconpb_naopertube`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proconpb_naopertube`.`endereco` ;

CREATE TABLE IF NOT EXISTS `proconpb_naopertube`.`endereco` (
  `id_endereco` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(8) NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(10) NOT NULL,
  `complemento` TINYTEXT CHARACTER SET 'utf8' NULL,
  UNIQUE INDEX `id_endereco_UNIQUE` (`id_endereco` ASC),
  PRIMARY KEY (`id_endereco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proconpb_naopertube`.`pessoa_fisica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proconpb_naopertube`.`pessoa_fisica` ;

CREATE TABLE IF NOT EXISTS `proconpb_naopertube`.`pessoa_fisica` (
  `nome` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `cpf` VARCHAR(14) CHARACTER SET 'utf8' NOT NULL,
  `rg` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `org` VARCHAR(5) CHARACTER SET 'utf8' NOT NULL,
  `uf` VARCHAR(2) CHARACTER SET 'utf8' NOT NULL,
  `data_expedicao` VARCHAR(8) CHARACTER SET 'utf8' NOT NULL,
  `usuario_id_usuario` INT NOT NULL AUTO_INCREMENT,
  `itens_bloqueio_id_itens` INT NOT NULL,
  `endereco_id_endereco` INT NOT NULL,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC),
  UNIQUE INDEX `usuario_id_usuario_UNIQUE` (`usuario_id_usuario` ASC),
  UNIQUE INDEX `itens_bloqueio_id_itens_UNIQUE` (`itens_bloqueio_id_itens` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proconpb_naopertube`.`pessoa_juridica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proconpb_naopertube`.`pessoa_juridica` ;

CREATE TABLE IF NOT EXISTS `proconpb_naopertube`.`pessoa_juridica` (
  `nome` VARCHAR(35) NOT NULL,
  `cnpj` VARCHAR(17) NOT NULL,
  `usuario_id_usuario` INT NOT NULL AUTO_INCREMENT,
  `itens_bloqueio_id_itens` INT NOT NULL,
  `endereco_id_endereco` INT NOT NULL,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC),
  UNIQUE INDEX `usuario_id_usuario_UNIQUE` (`usuario_id_usuario` ASC),
  UNIQUE INDEX `itens_bloqueio_id_itens_UNIQUE` (`itens_bloqueio_id_itens` ASC),
  PRIMARY KEY (`usuario_id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proconpb_naopertube`.`telemarketing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proconpb_naopertube`.`telemarketing` ;

CREATE TABLE IF NOT EXISTS `proconpb_naopertube`.`telemarketing` (
  `status_ativo` INT NOT NULL,
  `pessoa_juridica_usuario_id_usuario` INT NOT NULL,
  UNIQUE INDEX `pessoa_juridica_usuario_id_usuario_UNIQUE` (`pessoa_juridica_usuario_id_usuario` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proconpb_naopertube`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proconpb_naopertube`.`admin` ;

CREATE TABLE IF NOT EXISTS `proconpb_naopertube`.`admin` (
  `nome` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  UNIQUE INDEX `usuario_id_usuario_UNIQUE` (`usuario_id_usuario` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  PRIMARY KEY (`usuario_id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
