-- MySQL Script generated by MySQL Workbench
-- Qua 26 Out 2016 16:01:02 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema proconpb_naopertube
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `proconpb_naopertube` ;

-- -----------------------------------------------------
-- Schema proconpb_naopertube
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proconpb_naopertube` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `proconpb_naopertube` ;

-- -----------------------------------------------------
-- Table `proconpb_naopertube`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proconpb_naopertube`.`usuario` ;

CREATE TABLE IF NOT EXISTS `proconpb_naopertube`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `senha` VARCHAR(60) CHARACTER SET 'utf8' NOT NULL,
  UNIQUE INDEX `id_usuario_UNIQUE` (`id_usuario` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci
PACK_KEYS = DEFAULT;


-- -----------------------------------------------------
-- Table `proconpb_naopertube`.`pessoa_fisica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proconpb_naopertube`.`pessoa_fisica` ;

CREATE TABLE IF NOT EXISTS `proconpb_naopertube`.`pessoa_fisica` (
  `nome` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `cpf` VARCHAR(14) CHARACTER SET 'utf8' NOT NULL,
  `rg` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `org` VARCHAR(5) CHARACTER SET 'utf8' NOT NULL,
  `uf` VARCHAR(2) CHARACTER SET 'utf8' NOT NULL,
  `data_expedicao` VARCHAR(8) CHARACTER SET 'utf8' NOT NULL,
  `usuario_id_usuario` INT NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC),
  PRIMARY KEY (`usuario_id_usuario`),
  UNIQUE INDEX `usuario_id_usuario_UNIQUE` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_pessoa_fisica_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `proconpb_naopertube`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proconpb_naopertube`.`telefone`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proconpb_naopertube`.`telefone`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `telefone` (
  `status_bloqueio` int(11) NOT NULL,
  `data_cadastro` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `data_atualizacao` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `telefone_numero` varchar(45) CHARACTER SET utf8 NOT NULL,
  `usuario_id_usuario` int(11) NOT NULL,
  PRIMARY KEY (`usuario_id_usuario`),
  UNIQUE KEY `telefone_numero_UNIQUE` (`telefone_numero`),
  CONSTRAINT `fk_telefone_usuario1` FOREIGN KEY (`usuario_id_usuario`) REFERENCES `usuario` (`id_usuario`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proconpb_naopertube`.`pessoa_juridica`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proconpb_naopertube`.`pessoa_juridica` ;

CREATE TABLE IF NOT EXISTS `proconpb_naopertube`.`pessoa_juridica` (
  `nome` VARCHAR(35) CHARACTER SET 'utf8' NOT NULL,
  `cnpj` VARCHAR(17) CHARACTER SET 'utf8' NOT NULL,
  `usuario_id_usuario` INT NOT NULL AUTO_INCREMENT,
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC),
  UNIQUE INDEX `usuario_id_usuario_UNIQUE` (`usuario_id_usuario` ASC),
  PRIMARY KEY (`usuario_id_usuario`),
  CONSTRAINT `fk_pessoa_juridica_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `proconpb_naopertube`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proconpb_naopertube`.`telemarketing`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proconpb_naopertube`.`telemarketing` ;

CREATE TABLE IF NOT EXISTS `proconpb_naopertube`.`telemarketing` (
  `status_ativo` INT NOT NULL,
  `pessoa_juridica_usuario_id_usuario` INT NOT NULL,
  UNIQUE INDEX `pessoa_juridica_usuario_id_usuario_UNIQUE` (`pessoa_juridica_usuario_id_usuario` ASC),
  CONSTRAINT `fk_telemarketing_pessoa_juridica1`
    FOREIGN KEY (`pessoa_juridica_usuario_id_usuario`)
    REFERENCES `proconpb_naopertube`.`pessoa_juridica` (`usuario_id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proconpb_naopertube`.`endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proconpb_naopertube`.`endereco` ;

CREATE TABLE IF NOT EXISTS `proconpb_naopertube`.`endereco` (
  `cep` VARCHAR(8) CHARACTER SET 'utf8' NOT NULL,
  `rua` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `bairro` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `cidade` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `numero` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL,
  `complemento` TINYTEXT CHARACTER SET 'utf8' NULL,
  `usuario_id_usuario` INT NOT NULL,
  PRIMARY KEY (`usuario_id_usuario`),
  INDEX `fk_endereco_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_endereco_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `proconpb_naopertube`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `proconpb_naopertube`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `proconpb_naopertube`.`admin` ;

CREATE TABLE IF NOT EXISTS `proconpb_naopertube`.`admin` (
  `nome` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `usuario_id_usuario` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_admin_usuario1_idx` (`usuario_id_usuario` ASC),
  UNIQUE INDEX `usuario_id_usuario_UNIQUE` (`usuario_id_usuario` ASC),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  PRIMARY KEY (`usuario_id_usuario`),
  CONSTRAINT `fk_admin_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `proconpb_naopertube`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
