<?
$estados = array(
    '0' => 'AC',
    '1' => 'AL',
    '2' => 'AM',
    '3' => 'AP',
    '4' => 'BA',
    '5' => 'CE',
    '6' => 'DF',
    '7' => 'ES',
    '8' => 'GO',
    '9' => 'MA',
    '10' => 'MT',
    '11' => 'MS',
    '12' => 'MG',
    '13' => 'PA',
    '14' => 'PB',
    '15' => 'PR',
    '16' => 'PE',
    '17' => 'PI',
    '18' => 'RJ',
    '19' => 'RN',
    '20' => 'RO',
    '21' => 'RS',
    '22' => 'RR',
    '23' => 'SC',
    '24' => 'SE',
    '25' => 'SP',
    '26' => 'TO',
    );
    <input <?php if(isset($_SESSION['erro-uf'])) echo 'class="input-w-3 is-danger"'; else echo 'class="input-w-3 is-sucess"'; ?> id="uf" name="uf" type="text" maxlength="2" placeholder="UF" required="" value="<?php  if(isset($_POST['uf'])) echo htmlspecialchars($_POST['uf']); ?>"  >
